name: CMake Build MIIT lib

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        compiler:
          - gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          vcpkg: false
          ninja: false
          cppcheck: false
      - name: Create CMake cache if missing
        run: cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE .
      - name: Build MIIT lib
        run: cmake --build .
      - name: Archive shared libs
        uses: actions/upload-artifact@v3
        with:
          name: libmiit
          path: ./**/(lib)?miit.${{ runner.os == 'Windows' && 'dll' || (runner.os == 'Linux' && 'so' || 'dylib') }}
      - name: Archive demo
        uses: actions/upload-artifact@v3
        with:
          name: demo
          path: ./demo/${{ runner.os == 'Windows' && 'Debug/demo.exe' || 'demo' }}
      - name: Run Demo
        run: ./demo/${{ runner.os == 'Windows' && 'Debug/demo.exe' || 'demo' }}