name: CMake Build MIIT lib

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        compiler:
          - gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          vcpkg: true
          ninja: false
      - name: Create CMake cache if missing
        run: cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE .
      - name: Build MIIT lib
        run: cmake --build . --config Release --verbose
      - name: Run tests
        run: ctest
      - name: Archive Unix-based shared libs
        if: ${{ runner.os != 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: libmiit
          path: libmiit.${{ runner.os == 'Linux' && 'so' || 'dylib' }}
      - name: Archive Windows shared libs
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: libmiit
          path: Release/miit.dll
      - name: Run Demo
        run: demo/${{ runner.os == 'Windows' && 'Release/demo.exe' || 'demo' }}
      - name: Archive demo
        uses: actions/upload-artifact@v3
        with:
          name: demo-${{ runner.os }}
          path: demo/${{ runner.os == 'Windows' && 'Release/demo.exe' || 'demo' }}