name: CMake Build MIIT lib

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        compiler:
          - gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          vcpkg: true
          ninja: false
          cppcheck: false
      - name: Create CMake cache if missing
        run: cmake .
      - name: Build MIIT lib
        run: cmake --build .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libmath-${{ runner.os }}
          path:
            lib/*
      - name: Run Demo
        run: demo/demo